-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Аптеки"
(
    "Отдел_Код" integer NOT NULL,
    "Отдел_Наименование" text COLLATE pg_catalog."default",
    CONSTRAINT "Аптеки_pkey" PRIMARY KEY ("Отдел_Код")
);

CREATE TABLE IF NOT EXISTS public."Группы_товаров"
(
    "Группа_Код" integer NOT NULL,
    "Группа_Наименование" text COLLATE pg_catalog."default",
    CONSTRAINT "Группы_товаров_pkey" PRIMARY KEY ("Группа_Код")
);

CREATE TABLE IF NOT EXISTS public."Продажи"
(
    "Группа_Код" integer NOT NULL,
    "Отдел_Код" integer NOT NULL,
    "Товар_Код" integer NOT NULL,
    "Дата" date,
    "Час" integer,
    "Количество" integer,
    "Сумма" numeric
);

CREATE TABLE IF NOT EXISTS public."Товары"
(
    "Товар_Код" integer NOT NULL,
    "Товар_Наименование" text COLLATE pg_catalog."default",
    "Группа_Код" integer,
    CONSTRAINT "Товары_pkey" PRIMARY KEY ("Товар_Код")
);

ALTER TABLE IF EXISTS public."Продажи"
    ADD CONSTRAINT "Группа_Код" FOREIGN KEY ("Группа_Код")
    REFERENCES public."Группы_товаров" ("Группа_Код") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Продажи"
    ADD CONSTRAINT "Отдел_Код" FOREIGN KEY ("Отдел_Код")
    REFERENCES public."Аптеки" ("Отдел_Код") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Продажи"
    ADD CONSTRAINT "Товар_Код" FOREIGN KEY ("Товар_Код")
    REFERENCES public."Товары" ("Товар_Код") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Товары"
    ADD CONSTRAINT "Группа_Код" FOREIGN KEY ("Группа_Код")
    REFERENCES public."Группы_товаров" ("Группа_Код") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;